import type {
  BaitDefinition,
  BaitPackDefinition,
  FishDefinition,
  GameCatalog,
  LocationDefinition,
  RodDefinition,
} from './types';

export const fishCatalog: FishDefinition[] = [
  {
    id: 'karas',
    name: 'Crucian Carp',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karas.webp',
  },
  {
    id: 'plotva',
    name: 'Roach',
    rarity: 'common',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/plotva.webp',
  },
  {
    id: 'ukleyka',
    name: 'Bleak',
    rarity: 'common',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/ukleyka.webp',
  },
  {
    id: 'peskar',
    name: 'Gudgeon',
    rarity: 'common',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.03,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/peskar.webp',
  },
  {
    id: 'krasnopyorka',
    name: 'Rudd',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/krasnopyorka.webp',
  },
  {
    id: 'gustera',
    name: 'Silver Bream',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/gustera.webp',
  },
  {
    id: 'verhoplavka',
    name: 'Sunbleak',
    rarity: 'common',
    meanWeightKg: 0.01,
    weightVarianceKg: 0.005,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/verhoplavka.webp',
  },
  {
    id: 'vyun',
    name: 'Loach',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/vyun.webp',
  },
  {
    id: 'okun',
    name: 'Perch',
    rarity: 'common',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.07,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/okun.webp',
  },
  {
    id: 'yorsh',
    name: 'Ruffe',
    rarity: 'common',
    meanWeightKg: 0.08,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yorsh.webp',
  },
  {
    id: 'rotan',
    name: 'Amur Sleeper',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/rotan.webp',
  },
  {
    id: 'lesch',
    name: 'Bream',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lesch.webp',
  },
  {
    id: 'pelyad',
    name: 'Peled',
    rarity: 'uncommon',
    meanWeightKg: 1.3,
    weightVarianceKg: 0.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/pelyad.webp',
  },
  {
    id: 'lin',
    name: 'Tench',
    rarity: 'uncommon',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lin.webp',
  },
  {
    id: 'yaz',
    name: 'Ide',
    rarity: 'uncommon',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yaz.webp',
  },
  {
    id: 'karp',
    name: 'Carp',
    rarity: 'rare',
    meanWeightKg: 2.5,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karp.webp',
  },
  {
    id: 'schuka',
    name: 'Pike',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/schuka.webp',
  },
  {
    id: 'ugor-european',
    name: 'European Eel',
    rarity: 'epic',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ugor_evropeyskiy.webp',
  },
  {
    id: 'som-european',
    name: 'Wels Catfish',
    rarity: 'epic',
    meanWeightKg: 8,
    weightVarianceKg: 4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/som.webp',
  },
  {
    id: 'koi-kohaku',
    name: 'Koi Carp (Kohaku)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kohaku.webp',
  },
  {
    id: 'koi-sanke',
    name: 'Koi Carp (Taisho Sanke)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_taisho_sanke.webp',
  },
  {
    id: 'koi-showa',
    name: 'Koi Carp (Showa Sanshoku)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_showa_sanshoku.webp',
  },
  {
    id: 'koi-utsuri',
    name: 'Koi Carp (Utsurimono)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_utsurimono.webp',
  },
  {
    id: 'koi-bekko',
    name: 'Koi Carp (Bekko)',
    rarity: 'mythic',
    meanWeightKg: 2.4,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_bekko.webp',
  },
  {
    id: 'koi-tancho',
    name: 'Koi Carp (Tancho)',
    rarity: 'mythic',
    meanWeightKg: 2.7,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_tancho.webp',
  },
  {
    id: 'koi-asagi',
    name: 'Koi Carp (Asagi)',
    rarity: 'mythic',
    meanWeightKg: 3.2,
    weightVarianceKg: 1.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_asagi.webp',
  },
  {
    id: 'koi-shusui',
    name: 'Koi Carp (Shusui)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_shusui.webp',
  },
  {
    id: 'koi-koromo',
    name: 'Koi Carp (Koromo)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_koromo.webp',
  },
  {
    id: 'koi-ginrin',
    name: 'Koi Carp (Kinginrin)',
    rarity: 'mythic',
    meanWeightKg: 2.3,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kinginrin.webp',
  },
  {
    id: 'koi-kawarimono',
    name: 'Koi Carp (Kawarimono)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kawarimono.webp',
  },
  {
    id: 'koi-ogon',
    name: 'Koi Carp (Ogon)',
    rarity: 'mythic',
    meanWeightKg: 3.4,
    weightVarianceKg: 1.7,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_ogon.webp',
  },
  {
    id: 'koi-hikari-moyomono',
    name: 'Koi Carp (Hikari Moyomono)',
    rarity: 'mythic',
    meanWeightKg: 2.9,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_hikari_moyomono.webp',
  },
  {
    id: 'koi-goshiki',
    name: 'Koi Carp (Goshiki)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_goshiki.webp',
  },
  {
    id: 'koi-kumonryu',
    name: 'Koi Carp (Kumonryu)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kumonryu.webp',
  },
  {
    id: 'koi-doitsu',
    name: 'Koi Carp (Doitsu-goi)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_doitsu.webp',
  },
];

export const baitCatalog: BaitDefinition[] = [
  {
    id: 'fresh-peaceful',
    name: 'Fresh Peaceful',
    displayName: 'Grain Crumble',
    water: 'fresh',
    isPredator: false,
    rarityBonus: 0,
    image: '/riverking/baits/grain_crumble.webp',
  },
  {
    id: 'fresh-predator',
    name: 'Fresh Predator',
    displayName: 'Brook Minnow',
    water: 'fresh',
    isPredator: true,
    rarityBonus: 0,
    image: '/riverking/baits/brook_minnow.webp',
  },
  {
    id: 'salt-peaceful',
    name: 'Sea Peaceful',
    displayName: 'Seaweed Strand',
    water: 'salt',
    isPredator: false,
    rarityBonus: 0,
    image: '/riverking/baits/seaweed_strand.webp',
  },
  {
    id: 'salt-predator',
    name: 'Sea Predator',
    displayName: 'Squid Rings',
    water: 'salt',
    isPredator: true,
    rarityBonus: 0,
    image: '/riverking/baits/squid_rings.webp',
  },
];

export const baitPackCatalog: BaitPackDefinition[] = [
  {
    id: 'fresh_topup_s',
    name: 'Freshwater Top-up S',
    description: '20 freshwater basics: 10 "Grain Crumble" and 10 "Brook Minnow"',
    water: 'fresh',
    priceCoins: 360,
    image: '/riverking/shop/fresh_topup_s.png',
    items: [
      { baitId: 'fresh-peaceful', quantity: 10 },
      { baitId: 'fresh-predator', quantity: 10 },
    ],
  },
  {
    id: 'fresh_stock_m',
    name: 'Freshwater Stock M',
    description: '50 freshwater basics: 25 "Grain Crumble" and 25 "Brook Minnow"',
    water: 'fresh',
    priceCoins: 825,
    image: '/riverking/shop/fresh_stock_m.png',
    items: [
      { baitId: 'fresh-peaceful', quantity: 25 },
      { baitId: 'fresh-predator', quantity: 25 },
    ],
  },
  {
    id: 'fresh_crate_l',
    name: 'Freshwater Crate L',
    description: '120 freshwater basics: 60 "Grain Crumble" and 60 "Brook Minnow"',
    water: 'fresh',
    priceCoins: 1875,
    image: '/riverking/shop/fresh_crate_l.png',
    items: [
      { baitId: 'fresh-peaceful', quantity: 60 },
      { baitId: 'fresh-predator', quantity: 60 },
    ],
  },
  {
    id: 'salt_topup_s',
    name: 'Saltwater Top-up S',
    description: '20 saltwater basics: 6 "Seaweed Strand" and 14 "Squid Rings"',
    water: 'salt',
    priceCoins: 675,
    image: '/riverking/shop/salt_topup_s.png',
    items: [
      { baitId: 'salt-peaceful', quantity: 6 },
      { baitId: 'salt-predator', quantity: 14 },
    ],
  },
  {
    id: 'salt_stock_m',
    name: 'Saltwater Stock M',
    description: '50 saltwater basics: 15 "Seaweed Strand" and 35 "Squid Rings"',
    water: 'salt',
    priceCoins: 1500,
    image: '/riverking/shop/salt_stock_m.png',
    items: [
      { baitId: 'salt-peaceful', quantity: 15 },
      { baitId: 'salt-predator', quantity: 35 },
    ],
  },
  {
    id: 'salt_crate_l',
    name: 'Saltwater Crate L',
    description: '120 saltwater basics: 40 "Seaweed Strand" and 80 "Squid Rings"',
    water: 'salt',
    priceCoins: 3300,
    image: '/riverking/shop/salt_crate_l.png',
    items: [
      { baitId: 'salt-peaceful', quantity: 40 },
      { baitId: 'salt-predator', quantity: 80 },
    ],
  },
];

export const locationCatalog: LocationDefinition[] = [
  {
    id: 'pond',
    name: 'Pond',
    description: 'The starter RiverKing location with freshwater fish and rare koi.',
    unlockLevel: 1,
    sizeMultiplier: 1,
    image: '/riverking/backgrounds/pond.webp',
    fishWeights: [
      { fishId: 'karas', weight: 1.1 },
      { fishId: 'plotva', weight: 1 },
      { fishId: 'ukleyka', weight: 0.7 },
      { fishId: 'peskar', weight: 0.7 },
      { fishId: 'krasnopyorka', weight: 0.7 },
      { fishId: 'gustera', weight: 0.5 },
      { fishId: 'verhoplavka', weight: 0.5 },
      { fishId: 'vyun', weight: 0.45 },
      { fishId: 'lesch', weight: 0.4 },
      { fishId: 'pelyad', weight: 0.3 },
      { fishId: 'lin', weight: 0.2 },
      { fishId: 'karp', weight: 0.15 },
      { fishId: 'koi-kohaku', weight: 0.01 },
      { fishId: 'koi-sanke', weight: 0.01 },
      { fishId: 'koi-showa', weight: 0.01 },
      { fishId: 'koi-utsuri', weight: 0.01 },
      { fishId: 'koi-bekko', weight: 0.01 },
      { fishId: 'koi-tancho', weight: 0.01 },
      { fishId: 'koi-asagi', weight: 0.01 },
      { fishId: 'koi-shusui', weight: 0.01 },
      { fishId: 'koi-koromo', weight: 0.01 },
      { fishId: 'koi-ginrin', weight: 0.01 },
      { fishId: 'koi-kawarimono', weight: 0.01 },
      { fishId: 'koi-ogon', weight: 0.01 },
      { fishId: 'koi-hikari-moyomono', weight: 0.01 },
      { fishId: 'koi-goshiki', weight: 0.01 },
      { fishId: 'koi-kumonryu', weight: 0.01 },
      { fishId: 'koi-doitsu', weight: 0.01 },
      { fishId: 'yorsh', weight: 0.7 },
      { fishId: 'rotan', weight: 0.6 },
      { fishId: 'okun', weight: 0.4 },
      { fishId: 'yaz', weight: 0.25 },
      { fishId: 'schuka', weight: 0.12 },
      { fishId: 'ugor-european', weight: 0.06 },
      { fishId: 'som-european', weight: 0.03 },
    ],
  },
];

export const rodCatalog: RodDefinition[] = [
  {
    id: 'spark',
    name: 'Spark',
    power: 1,
    unlockLevel: 1,
  },
];

export const gameCatalog: GameCatalog = {
  locations: locationCatalog,
  baits: baitCatalog,
  baitPacks: baitPackCatalog,
  rods: rodCatalog,
  fish: fishCatalog,
};

export const defaultLocationId = 'pond';

export const defaultBaitId = 'fresh-peaceful';

export const defaultRodId = 'spark';

export const findFish = (fishId: string): FishDefinition | null => {
  return fishCatalog.find((fish) => fish.id === fishId) ?? null;
};

export const findBait = (baitId: string): BaitDefinition | null => {
  return baitCatalog.find((bait) => bait.id === baitId) ?? null;
};

export const findBaitPack = (baitPackId: string): BaitPackDefinition | null => {
  return baitPackCatalog.find((pack) => pack.id === baitPackId) ?? null;
};

export const findLocation = (locationId: string): LocationDefinition | null => {
  return locationCatalog.find((location) => location.id === locationId) ?? null;
};

export const findRod = (rodId: string): RodDefinition | null => {
  return rodCatalog.find((rod) => rod.id === rodId) ?? null;
};
