import type {
  BaitDefinition,
  FishDefinition,
  GameCatalog,
  LocationDefinition,
  RodDefinition,
} from './types';

export const fishCatalog: FishDefinition[] = [
  {
    id: 'karas',
    name: 'Карась',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karas.webp',
  },
  {
    id: 'plotva',
    name: 'Плотва',
    rarity: 'common',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/plotva.webp',
  },
  {
    id: 'ukleyka',
    name: 'Уклейка',
    rarity: 'common',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/ukleyka.webp',
  },
  {
    id: 'peskar',
    name: 'Пескарь',
    rarity: 'common',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.03,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/peskar.webp',
  },
  {
    id: 'krasnopyorka',
    name: 'Краснопёрка',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/krasnopyorka.webp',
  },
  {
    id: 'gustera',
    name: 'Густера',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/gustera.webp',
  },
  {
    id: 'verhoplavka',
    name: 'Верхоплавка',
    rarity: 'common',
    meanWeightKg: 0.01,
    weightVarianceKg: 0.005,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/verhoplavka.webp',
  },
  {
    id: 'vyun',
    name: 'Вьюн',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/vyun.webp',
  },
  {
    id: 'okun',
    name: 'Окунь',
    rarity: 'common',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.07,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/okun.webp',
  },
  {
    id: 'yorsh',
    name: 'Ёрш',
    rarity: 'common',
    meanWeightKg: 0.08,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yorsh.webp',
  },
  {
    id: 'rotan',
    name: 'Ротан',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/rotan.webp',
  },
  {
    id: 'lesch',
    name: 'Лещ',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lesch.webp',
  },
  {
    id: 'pelyad',
    name: 'Пелядь',
    rarity: 'uncommon',
    meanWeightKg: 1.3,
    weightVarianceKg: 0.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/pelyad.webp',
  },
  {
    id: 'lin',
    name: 'Линь',
    rarity: 'uncommon',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lin.webp',
  },
  {
    id: 'yaz',
    name: 'Язь',
    rarity: 'uncommon',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yaz.webp',
  },
  {
    id: 'karp',
    name: 'Карп',
    rarity: 'rare',
    meanWeightKg: 2.5,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karp.webp',
  },
  {
    id: 'schuka',
    name: 'Щука',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/schuka.webp',
  },
  {
    id: 'ugor-european',
    name: 'Угорь европейский',
    rarity: 'epic',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ugor_evropeyskiy.webp',
  },
  {
    id: 'som-european',
    name: 'Сом европейский',
    rarity: 'epic',
    meanWeightKg: 8,
    weightVarianceKg: 4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/som.webp',
  },
  {
    id: 'koi-kohaku',
    name: 'Карп кои (Кохаку)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kohaku.webp',
  },
  {
    id: 'koi-sanke',
    name: 'Карп кои (Тайсё Сансёку)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_taisho_sanke.webp',
  },
  {
    id: 'koi-showa',
    name: 'Карп кои (Сёва Сансёку)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_showa_sanshoku.webp',
  },
  {
    id: 'koi-utsuri',
    name: 'Карп кои (Уцуримоно)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_utsurimono.webp',
  },
  {
    id: 'koi-bekko',
    name: 'Карп кои (Бэкко)',
    rarity: 'mythic',
    meanWeightKg: 2.4,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_bekko.webp',
  },
  {
    id: 'koi-tancho',
    name: 'Карп кои (Тантё)',
    rarity: 'mythic',
    meanWeightKg: 2.7,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_tancho.webp',
  },
  {
    id: 'koi-asagi',
    name: 'Карп кои (Асаги)',
    rarity: 'mythic',
    meanWeightKg: 3.2,
    weightVarianceKg: 1.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_asagi.webp',
  },
  {
    id: 'koi-shusui',
    name: 'Карп кои (Сюсуй)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_shusui.webp',
  },
  {
    id: 'koi-koromo',
    name: 'Карп кои (Коромо)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_koromo.webp',
  },
  {
    id: 'koi-ginrin',
    name: 'Карп кои (Кингинрин)',
    rarity: 'mythic',
    meanWeightKg: 2.3,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kinginrin.webp',
  },
  {
    id: 'koi-kawarimono',
    name: 'Карп кои (Каваримоно)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kawarimono.webp',
  },
  {
    id: 'koi-ogon',
    name: 'Карп кои (Огон)',
    rarity: 'mythic',
    meanWeightKg: 3.4,
    weightVarianceKg: 1.7,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_ogon.webp',
  },
  {
    id: 'koi-hikari-moyomono',
    name: 'Карп кои (Хикари-моёмоно)',
    rarity: 'mythic',
    meanWeightKg: 2.9,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_hikari_moyomono.webp',
  },
  {
    id: 'koi-goshiki',
    name: 'Карп кои (Госики)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_goshiki.webp',
  },
  {
    id: 'koi-kumonryu',
    name: 'Карп кои (Кумонрю)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kumonryu.webp',
  },
  {
    id: 'koi-doitsu',
    name: 'Карп кои (Дойцу-гои)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_doitsu.webp',
  },
];

export const baitCatalog: BaitDefinition[] = [
  {
    id: 'fresh-peaceful',
    name: 'Пресная мирная',
    displayName: 'Зерновая крошка',
    water: 'fresh',
    isPredator: false,
    rarityBonus: 0,
    image: '/riverking/baits/grain_crumble.webp',
  },
  {
    id: 'fresh-predator',
    name: 'Пресная хищная',
    displayName: 'Ручейный малек',
    water: 'fresh',
    isPredator: true,
    rarityBonus: 0,
    image: '/riverking/baits/brook_minnow.webp',
  },
  {
    id: 'salt-peaceful',
    name: 'Морская мирная',
    displayName: 'Морская водоросль',
    water: 'salt',
    isPredator: false,
    rarityBonus: 0,
    image: '/riverking/baits/seaweed_strand.webp',
  },
  {
    id: 'salt-predator',
    name: 'Морская хищная',
    displayName: 'Кольца кальмара',
    water: 'salt',
    isPredator: true,
    rarityBonus: 0,
    image: '/riverking/baits/squid_rings.webp',
  },
];

export const locationCatalog: LocationDefinition[] = [
  {
    id: 'pond',
    name: 'Пруд',
    description: 'Стартовая локация RiverKing с пресной рыбой и редкими кои.',
    unlockLevel: 1,
    sizeMultiplier: 1,
    image: '/riverking/backgrounds/pond.webp',
    fishWeights: [
      { fishId: 'karas', weight: 1.1 },
      { fishId: 'plotva', weight: 1 },
      { fishId: 'ukleyka', weight: 0.7 },
      { fishId: 'peskar', weight: 0.7 },
      { fishId: 'krasnopyorka', weight: 0.7 },
      { fishId: 'gustera', weight: 0.5 },
      { fishId: 'verhoplavka', weight: 0.5 },
      { fishId: 'vyun', weight: 0.45 },
      { fishId: 'lesch', weight: 0.4 },
      { fishId: 'pelyad', weight: 0.3 },
      { fishId: 'lin', weight: 0.2 },
      { fishId: 'karp', weight: 0.15 },
      { fishId: 'koi-kohaku', weight: 0.01 },
      { fishId: 'koi-sanke', weight: 0.01 },
      { fishId: 'koi-showa', weight: 0.01 },
      { fishId: 'koi-utsuri', weight: 0.01 },
      { fishId: 'koi-bekko', weight: 0.01 },
      { fishId: 'koi-tancho', weight: 0.01 },
      { fishId: 'koi-asagi', weight: 0.01 },
      { fishId: 'koi-shusui', weight: 0.01 },
      { fishId: 'koi-koromo', weight: 0.01 },
      { fishId: 'koi-ginrin', weight: 0.01 },
      { fishId: 'koi-kawarimono', weight: 0.01 },
      { fishId: 'koi-ogon', weight: 0.01 },
      { fishId: 'koi-hikari-moyomono', weight: 0.01 },
      { fishId: 'koi-goshiki', weight: 0.01 },
      { fishId: 'koi-kumonryu', weight: 0.01 },
      { fishId: 'koi-doitsu', weight: 0.01 },
      { fishId: 'yorsh', weight: 0.7 },
      { fishId: 'rotan', weight: 0.6 },
      { fishId: 'okun', weight: 0.4 },
      { fishId: 'yaz', weight: 0.25 },
      { fishId: 'schuka', weight: 0.12 },
      { fishId: 'ugor-european', weight: 0.06 },
      { fishId: 'som-european', weight: 0.03 },
    ],
  },
];

export const rodCatalog: RodDefinition[] = [
  {
    id: 'spark',
    name: 'Искра',
    power: 1,
    unlockLevel: 1,
  },
];

export const gameCatalog: GameCatalog = {
  locations: locationCatalog,
  baits: baitCatalog,
  rods: rodCatalog,
  fish: fishCatalog,
};

export const defaultLocationId = 'pond';

export const defaultBaitId = 'fresh-peaceful';

export const defaultRodId = 'spark';

export const findFish = (fishId: string): FishDefinition | null => {
  return fishCatalog.find((fish) => fish.id === fishId) ?? null;
};

export const findBait = (baitId: string): BaitDefinition | null => {
  return baitCatalog.find((bait) => bait.id === baitId) ?? null;
};

export const findLocation = (locationId: string): LocationDefinition | null => {
  return locationCatalog.find((location) => location.id === locationId) ?? null;
};

export const findRod = (rodId: string): RodDefinition | null => {
  return rodCatalog.find((rod) => rod.id === rodId) ?? null;
};
