import type { FishDefinition, LocationDefinition } from './types';

export const fishCatalog: FishDefinition[] = [
  {
    id: 'plotva',
    name: 'Roach',
    rarity: 'common',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/plotva.webp',
  },
  {
    id: 'karas',
    name: 'Crucian Carp',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karas.webp',
  },
  {
    id: 'ukleyka',
    name: 'Bleak',
    rarity: 'common',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/ukleyka.webp',
  },
  {
    id: 'peskar',
    name: 'Gudgeon',
    rarity: 'common',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.03,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/peskar.webp',
  },
  {
    id: 'gustera',
    name: 'Blue Bream',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/gustera.webp',
  },
  {
    id: 'krasnopyorka',
    name: 'Rudd',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/krasnopyorka.webp',
  },
  {
    id: 'elets',
    name: 'Dace',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/elets.webp',
  },
  {
    id: 'verhoplavka',
    name: 'Topmouth Gudgeon',
    rarity: 'common',
    meanWeightKg: 0.01,
    weightVarianceKg: 0.005,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/verhoplavka.webp',
  },
  {
    id: 'golyan',
    name: 'Minnow',
    rarity: 'common',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/golyan.webp',
  },
  {
    id: 'prohilodus',
    name: 'Stripetail Prochilodus',
    rarity: 'common',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/prohilodus.webp',
  },
  {
    id: 'otocinklyus',
    name: 'Banded Otocinclus',
    rarity: 'common',
    meanWeightKg: 0.01,
    weightVarianceKg: 0.005,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/otocinklyus.webp',
  },
  {
    id: 'tetra-neonovaya',
    name: 'Neon Tetra',
    rarity: 'common',
    meanWeightKg: 0.003,
    weightVarianceKg: 0.0015,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_neonovaya.webp',
  },
  {
    id: 'tetra-kardinal',
    name: 'Cardinal Tetra',
    rarity: 'common',
    meanWeightKg: 0.003,
    weightVarianceKg: 0.0015,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_kardinal.webp',
  },
  {
    id: 'nannostomus',
    name: 'Three-Stripe Pencilfish',
    rarity: 'common',
    meanWeightKg: 0.004,
    weightVarianceKg: 0.002,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/nannostomus.webp',
  },
  {
    id: 'vyun',
    name: 'Weather Loach',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/vyun.webp',
  },
  {
    id: 'vobla',
    name: 'Caspian Roach',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/vobla.webp',
  },
  {
    id: 'tetra-rodostomus',
    name: 'Rummy-nose Tetra',
    rarity: 'common',
    meanWeightKg: 0.0035,
    weightVarianceKg: 0.0015,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_rodostomus.webp',
  },
  {
    id: 'karnegiella-mramornaya',
    name: 'Marbled Hatchetfish',
    rarity: 'common',
    meanWeightKg: 0.004,
    weightVarianceKg: 0.002,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karnegiella_mramornaya.webp',
  },
  {
    id: 'tetra-limonnaya',
    name: 'Lemon Tetra',
    rarity: 'common',
    meanWeightKg: 0.004,
    weightVarianceKg: 0.002,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_limonnaya.webp',
  },
  {
    id: 'tetra-black-neon',
    name: 'Black Neon Tetra',
    rarity: 'common',
    meanWeightKg: 0.0035,
    weightVarianceKg: 0.0015,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_black_neon.webp',
  },
  {
    id: 'tetra-pingvin',
    name: 'Penguin Tetra',
    rarity: 'common',
    meanWeightKg: 0.005,
    weightVarianceKg: 0.0025,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_pingvin.webp',
  },
  {
    id: 'tetra-ognennaya',
    name: 'Ember Tetra',
    rarity: 'common',
    meanWeightKg: 0.0025,
    weightVarianceKg: 0.0012,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_ognennaya.webp',
  },
  {
    id: 'nannostomus-marginatus',
    name: 'Dwarf Pencilfish',
    rarity: 'common',
    meanWeightKg: 0.003,
    weightVarianceKg: 0.0015,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/nannostomus_marginatus.webp',
  },
  {
    id: 'okun',
    name: 'Perch',
    rarity: 'common',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.07,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/okun.webp',
  },
  {
    id: 'rotan',
    name: 'Rotan',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.05,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/rotan.webp',
  },
  {
    id: 'yorsh',
    name: 'Ruffe',
    rarity: 'common',
    meanWeightKg: 0.08,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yorsh.webp',
  },
  {
    id: 'bersh',
    name: 'Volga Pikeperch',
    rarity: 'common',
    meanWeightKg: 1.1,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/bersh.webp',
  },
  {
    id: 'mecherot-common',
    name: 'Common Freshwater Barracuda',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.15,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/mecherot_common.webp',
  },
  {
    id: 'tatiya-leopardovaya',
    name: 'Leopard Tatia',
    rarity: 'common',
    meanWeightKg: 0.08,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/tatiya_leopardovaya.webp',
  },
  {
    id: 'cihlazoma-mezonauta',
    name: 'Flag Cichlid',
    rarity: 'common',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.12,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/cihlazoma_mezonauta.webp',
  },
  {
    id: 'lin',
    name: 'Tench',
    rarity: 'uncommon',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lin.webp',
  },
  {
    id: 'chehon',
    name: 'Sabrefish',
    rarity: 'uncommon',
    meanWeightKg: 0.4,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/chehon.webp',
  },
  {
    id: 'sig',
    name: 'Common Whitefish',
    rarity: 'uncommon',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/sig.webp',
  },
  {
    id: 'lesch',
    name: 'Bream',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/lesch.webp',
  },
  {
    id: 'paku-cherniy',
    name: 'Black Pacu',
    rarity: 'uncommon',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/paku_cherniy.webp',
  },
  {
    id: 'ancistrus',
    name: 'Common Bristlenose',
    rarity: 'uncommon',
    meanWeightKg: 0.1,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/ancistrus.webp',
  },
  {
    id: 'tetra-chernaya',
    name: 'Black Skirt Tetra',
    rarity: 'uncommon',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tetra_chernaya.webp',
  },
  {
    id: 'skalyaria-common',
    name: 'Freshwater Angelfish',
    rarity: 'uncommon',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.08,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/skalyaria_common.webp',
  },
  {
    id: 'apistogramma-agassiza',
    name: "Agassiz's Cichlid",
    rarity: 'uncommon',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/apistogramma_agassiza.webp',
  },
  {
    id: 'koridorus-panda',
    name: 'Panda Cory',
    rarity: 'uncommon',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koridorus_panda.webp',
  },
  {
    id: 'pelyad',
    name: 'Peled Whitefish',
    rarity: 'uncommon',
    meanWeightKg: 1.3,
    weightVarianceKg: 0.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/pelyad.webp',
  },
  {
    id: 'metinnis-serebristiy',
    name: 'Silver Dollar',
    rarity: 'uncommon',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/metinnis_serebristiy.webp',
  },
  {
    id: 'koridoras-shterba',
    name: "Sterba's Corydoras",
    rarity: 'uncommon',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.03,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koridoras_shterba.webp',
  },
  {
    id: 'torakatum',
    name: 'Hoplo Catfish',
    rarity: 'uncommon',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/torakatum.webp',
  },
  {
    id: 'leporinus-polosatiy',
    name: 'Banded Leporinus',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/leporinus_polosatiy.webp',
  },
  {
    id: 'nalim',
    name: 'Burbot',
    rarity: 'uncommon',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.8,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/nalim.webp',
  },
  {
    id: 'golavl',
    name: 'Chub',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/golavl.webp',
  },
  {
    id: 'yaz',
    name: 'Ide',
    rarity: 'uncommon',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/yaz.webp',
  },
  {
    id: 'piranya-krasnopuzaya',
    name: 'Red-bellied Piranha',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/piranya_krasnopuzaya.webp',
  },
  {
    id: 'gimnotus-ugrevidniy',
    name: 'Banded Knifefish',
    rarity: 'uncommon',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.15,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/gimnotus_ugrevidniy.webp',
  },
  {
    id: 'pimelodus-pyatnistiy',
    name: 'Spotted Pimelodus',
    rarity: 'uncommon',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.1,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/pimelodus_pyatnistiy.webp',
  },
  {
    id: 'cihlazoma-severum',
    name: 'Severum Cichlid',
    rarity: 'uncommon',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.25,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/cihlazoma_severum.webp',
  },
  {
    id: 'tolstolobik',
    name: 'Bighead Carp',
    rarity: 'rare',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tolstolobik.webp',
  },
  {
    id: 'beliy-amur',
    name: 'Grass Carp',
    rarity: 'rare',
    meanWeightKg: 3.5,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/beliy_amur.webp',
  },
  {
    id: 'karp',
    name: 'Carp',
    rarity: 'rare',
    meanWeightKg: 2.5,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/karp.webp',
  },
  {
    id: 'ramirezi',
    name: 'Ram Cichlid',
    rarity: 'rare',
    meanWeightKg: 0.05,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/ramirezi.webp',
  },
  {
    id: 'omul-arcticheskiy',
    name: 'Arctic Omul',
    rarity: 'rare',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/omul_arcticheskiy.webp',
  },
  {
    id: 'muksun',
    name: 'Muksun Whitefish',
    rarity: 'rare',
    meanWeightKg: 2.2,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/muksun.webp',
  },
  {
    id: 'pterigopliht-parchoviy',
    name: 'Sailfin Pleco',
    rarity: 'rare',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/pterigopliht_parchoviy.webp',
  },
  {
    id: 'paku-krasnobryuhiy',
    name: 'Red-bellied Pacu',
    rarity: 'rare',
    meanWeightKg: 8,
    weightVarianceKg: 4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/paku_krasnobryuhiy.webp',
  },
  {
    id: 'sudak',
    name: 'Zander',
    rarity: 'rare',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/sudak.webp',
  },
  {
    id: 'harius',
    name: 'Grayling',
    rarity: 'rare',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.25,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/harius.webp',
  },
  {
    id: 'forel-ruchevaya',
    name: 'Brook Trout',
    rarity: 'rare',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.6,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/forel_ruchevaya.webp',
  },
  {
    id: 'zhereh',
    name: 'Asp',
    rarity: 'rare',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/zhereh.webp',
  },
  {
    id: 'schuka',
    name: 'Pike',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/schuka.webp',
  },
  {
    id: 'bikuda',
    name: 'Bicuda',
    rarity: 'rare',
    meanWeightKg: 1,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/bikuda.webp',
  },
  {
    id: 'oskar',
    name: 'Oscar Cichlid',
    rarity: 'rare',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/oskar.webp',
  },
  {
    id: 'piranya-chernaya',
    name: 'Black Piranha',
    rarity: 'rare',
    meanWeightKg: 1.3,
    weightVarianceKg: 0.6,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/piranya_chernaya.webp',
  },
  {
    id: 'schuchya-cihlida',
    name: 'Pike Cichlid',
    rarity: 'rare',
    meanWeightKg: 0.9,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/schuchya_cihlida.webp',
  },
  {
    id: 'ryba-list-amazonskaya',
    name: 'Amazon Leaf Fish',
    rarity: 'rare',
    meanWeightKg: 0.06,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ryba_list_amazonskaya.webp',
  },
  {
    id: 'mecherot-pyatnistiy',
    name: 'Spotted Freshwater Barracuda',
    rarity: 'rare',
    meanWeightKg: 1.4,
    weightVarianceKg: 0.6,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/mecherot_pyatnistiy.webp',
  },
  {
    id: 'sterlyad',
    name: 'Sterlet',
    rarity: 'epic',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/sterlyad.webp',
  },
  {
    id: 'tambaki',
    name: 'Brown Pacu',
    rarity: 'epic',
    meanWeightKg: 12,
    weightVarianceKg: 6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/tambaki.webp',
  },
  {
    id: 'diskus',
    name: 'Common Discus',
    rarity: 'epic',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/diskus.webp',
  },
  {
    id: 'skalyaria-altum',
    name: 'Altum Angelfish',
    rarity: 'epic',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/skalyaria_altum.webp',
  },
  {
    id: 'ugor-evropeyskiy',
    name: 'European Eel',
    rarity: 'epic',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ugor_evropeyskiy.webp',
  },
  {
    id: 'som',
    name: 'European Catfish',
    rarity: 'epic',
    meanWeightKg: 8,
    weightVarianceKg: 4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/som.webp',
  },
  {
    id: 'golets-arkticheskiy',
    name: 'Arctic Char',
    rarity: 'epic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/golets_arkticheskiy.webp',
  },
  {
    id: 'forel-kumzha',
    name: 'Brown Trout',
    rarity: 'epic',
    meanWeightKg: 4,
    weightVarianceKg: 1.5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/forel_kumzha.webp',
  },
  {
    id: 'ugor-elektricheskiy',
    name: 'Electric Eel',
    rarity: 'epic',
    meanWeightKg: 15,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ugor_elektricheskiy.webp',
  },
  {
    id: 'krasnohvostiy-som',
    name: 'Redtail Catfish',
    rarity: 'epic',
    meanWeightKg: 30,
    weightVarianceKg: 12,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/krasnohvostiy_som.webp',
  },
  {
    id: 'aymara',
    name: 'Aimara',
    rarity: 'epic',
    meanWeightKg: 8,
    weightVarianceKg: 4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/aymara.webp',
  },
  {
    id: 'surubin',
    name: 'Tiger Shovelnose',
    rarity: 'epic',
    meanWeightKg: 10,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/surubin.webp',
  },
  {
    id: 'pavliniy-okun',
    name: 'Peacock Bass',
    rarity: 'epic',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/pavliniy_okun.webp',
  },
  {
    id: 'lenok',
    name: 'Lenok Trout',
    rarity: 'epic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/lenok.webp',
  },
  {
    id: 'ryba-nozh-chernaya',
    name: 'Black Ghost Knifefish',
    rarity: 'epic',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/ryba_nozh_chernaya.webp',
  },
  {
    id: 'som-veslonosiy',
    name: 'Paddlefish',
    rarity: 'epic',
    meanWeightKg: 7,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/som_veslonosiy.webp',
  },
  {
    id: 'brahiplatistoma-tigrovaya',
    name: 'Tiger Catfish',
    rarity: 'epic',
    meanWeightKg: 12,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/brahiplatistoma_tigrovaya.webp',
  },
  {
    id: 'koi-kohaku',
    name: 'Koi (Kohaku)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kohaku.webp',
  },
  {
    id: 'koi-taisho-sanke',
    name: 'Koi (Taisho Sanshoku)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_taisho_sanke.webp',
  },
  {
    id: 'koi-showa-sanshoku',
    name: 'Koi (Showa Sanshoku)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_showa_sanshoku.webp',
  },
  {
    id: 'koi-utsurimono',
    name: 'Koi (Utsurimono)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_utsurimono.webp',
  },
  {
    id: 'koi-bekko',
    name: 'Koi (Bekko)',
    rarity: 'mythic',
    meanWeightKg: 2.4,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_bekko.webp',
  },
  {
    id: 'koi-tancho',
    name: 'Koi (Tancho)',
    rarity: 'mythic',
    meanWeightKg: 2.7,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_tancho.webp',
  },
  {
    id: 'koi-asagi',
    name: 'Koi (Asagi)',
    rarity: 'mythic',
    meanWeightKg: 3.2,
    weightVarianceKg: 1.6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_asagi.webp',
  },
  {
    id: 'koi-shusui',
    name: 'Koi (Shusui)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.4,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_shusui.webp',
  },
  {
    id: 'koi-koromo',
    name: 'Koi (Koromo)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_koromo.webp',
  },
  {
    id: 'koi-kinginrin',
    name: 'Koi (Kinginrin)',
    rarity: 'mythic',
    meanWeightKg: 2.3,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kinginrin.webp',
  },
  {
    id: 'koi-kawarimono',
    name: 'Koi (Kawarimono)',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kawarimono.webp',
  },
  {
    id: 'koi-ogon',
    name: 'Koi (Ogon)',
    rarity: 'mythic',
    meanWeightKg: 3.4,
    weightVarianceKg: 1.7,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_ogon.webp',
  },
  {
    id: 'koi-hikari-moyomono',
    name: 'Koi (Hikari Moyomono)',
    rarity: 'mythic',
    meanWeightKg: 2.9,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_hikari_moyomono.webp',
  },
  {
    id: 'koi-goshiki',
    name: 'Koi (Goshiki)',
    rarity: 'mythic',
    meanWeightKg: 2.8,
    weightVarianceKg: 1.3,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_goshiki.webp',
  },
  {
    id: 'koi-kumonryu',
    name: 'Koi (Kumonryu)',
    rarity: 'mythic',
    meanWeightKg: 2.5,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_kumonryu.webp',
  },
  {
    id: 'koi-doitsu',
    name: 'Koi (Doitsu-goi)',
    rarity: 'mythic',
    meanWeightKg: 2.6,
    weightVarianceKg: 1.1,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/koi_doitsu.webp',
  },
  {
    id: 'cherniy-amur',
    name: 'Black Amur',
    rarity: 'mythic',
    meanWeightKg: 12,
    weightVarianceKg: 5,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/cherniy_amur.webp',
  },
  {
    id: 'zmeegolov-severniy',
    name: 'Northern Snakehead',
    rarity: 'mythic',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/zmeegolov_severniy.webp',
  },
  {
    id: 'amurskaya-schuka',
    name: 'Amur Pike',
    rarity: 'mythic',
    meanWeightKg: 5,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/amurskaya_schuka.webp',
  },
  {
    id: 'kristivomer',
    name: 'Lake Trout',
    rarity: 'mythic',
    meanWeightKg: 10,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/kristivomer.webp',
  },
  {
    id: 'dunaiskiy-losos',
    name: 'Danube Salmon (Huchen)',
    rarity: 'mythic',
    meanWeightKg: 10,
    weightVarianceKg: 4,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/dunaiskiy_losos.webp',
  },
  {
    id: 'zungaro',
    name: 'Zungaro Catfish',
    rarity: 'mythic',
    meanWeightKg: 25,
    weightVarianceKg: 10,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/zungaro.webp',
  },
  {
    id: 'skat-motoro',
    name: 'Motoro Stingray',
    rarity: 'mythic',
    meanWeightKg: 12,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/skat_motoro.webp',
  },
  {
    id: 'payara',
    name: 'Payara',
    rarity: 'mythic',
    meanWeightKg: 7,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/payara.webp',
  },
  {
    id: 'osetr',
    name: 'European Sturgeon',
    rarity: 'legendary',
    meanWeightKg: 12,
    weightVarianceKg: 6,
    isPredator: false,
    water: 'fresh',
    image: '/riverking/fish/osetr.webp',
  },
  {
    id: 'taymen',
    name: 'Taimen',
    rarity: 'legendary',
    meanWeightKg: 15,
    weightVarianceKg: 7,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/taymen.webp',
  },
  {
    id: 'arapayma',
    name: 'Arapaima',
    rarity: 'legendary',
    meanWeightKg: 80,
    weightVarianceKg: 30,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/arapayma.webp',
  },
  {
    id: 'piraiba',
    name: 'Piraiba',
    rarity: 'legendary',
    meanWeightKg: 70,
    weightVarianceKg: 35,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/piraiba.webp',
  },
  {
    id: 'aravana-chernaya',
    name: 'Black Arowana',
    rarity: 'legendary',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'fresh',
    image: '/riverking/fish/aravana_chernaya.webp',
  },
  {
    id: 'seld',
    name: 'Herring',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/seld.webp',
  },
  {
    id: 'kilka',
    name: 'Sprat',
    rarity: 'common',
    meanWeightKg: 0.03,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/kilka.webp',
  },
  {
    id: 'mojva',
    name: 'Capelin',
    rarity: 'common',
    meanWeightKg: 0.04,
    weightVarianceKg: 0.015,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/mojva.webp',
  },
  {
    id: 'sardina',
    name: 'Sardine',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/sardina.webp',
  },
  {
    id: 'anchous',
    name: 'European Anchovy',
    rarity: 'common',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/anchous.webp',
  },
  {
    id: 'kefal-pyatnistaya',
    name: 'Spotted Mullet',
    rarity: 'common',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.4,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/kefal_pyatnistaya.webp',
  },
  {
    id: 'anchous-tropicheskiy',
    name: 'Tropical Anchovy',
    rarity: 'common',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/anchous_tropicheskiy.webp',
  },
  {
    id: 'sardina-indiyskaya',
    name: 'Indian Sardine',
    rarity: 'common',
    meanWeightKg: 0.1,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/sardina_indiyskaya.webp',
  },
  {
    id: 'damsel-siniy',
    name: 'Blue Damselfish',
    rarity: 'common',
    meanWeightKg: 0.04,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/damsel_siniy.webp',
  },
  {
    id: 'fuziler-zheltohvostiy',
    name: 'Yellowtail Fusilier',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/fuziler_zheltohvostiy.webp',
  },
  {
    id: 'taran',
    name: 'Black Sea Roach',
    rarity: 'common',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/taran.webp',
  },
  {
    id: 'ryba-kloun',
    name: 'Clownfish',
    rarity: 'common',
    meanWeightKg: 0.15,
    weightVarianceKg: 0.06,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/ryba_kloun.webp',
  },
  {
    id: 'kefal-mangrovaya',
    name: 'Mangrove Mullet',
    rarity: 'common',
    meanWeightKg: 0.5,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/kefal_mangrovaya.webp',
  },
  {
    id: 'seld-tihookeanskaya',
    name: 'Pacific Herring',
    rarity: 'common',
    meanWeightKg: 0.35,
    weightVarianceKg: 0.12,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/seld_tihookeanskaya.webp',
  },
  {
    id: 'hromis-rifoviy',
    name: 'Reef Chromis',
    rarity: 'common',
    meanWeightKg: 0.06,
    weightVarianceKg: 0.02,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/hromis_rifoviy.webp',
  },
  {
    id: 'damsel-zheltohvostiy',
    name: 'Yellowtail Damselfish',
    rarity: 'common',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.025,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/damsel_zheltohvostiy.webp',
  },
  {
    id: 'morskoy-konek',
    name: 'Seahorse',
    rarity: 'common',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.008,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/morskoy_konek.webp',
  },
  {
    id: 'stavrida',
    name: 'Horse Mackerel',
    rarity: 'common',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/stavrida.webp',
  },
  {
    id: 'koryushka',
    name: 'Smelt',
    rarity: 'common',
    meanWeightKg: 0.06,
    weightVarianceKg: 0.02,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/koryushka.webp',
  },
  {
    id: 'bychyok',
    name: 'Round Goby',
    rarity: 'common',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.06,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/bychyok.webp',
  },
  {
    id: 'klyuvach-pacificocean',
    name: 'Pacific Snipefish',
    rarity: 'common',
    meanWeightKg: 1.6,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/klyuvach_pacificocean.webp',
  },
  {
    id: 'lucian-serebristo-pyatnistiy',
    name: 'Silverspot Snapper',
    rarity: 'common',
    meanWeightKg: 1,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/lucian_serebristo-pyatnistiy.webp',
  },
  {
    id: 'skorpena-borodataya',
    name: 'Bearded Scorpionfish',
    rarity: 'common',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/skorpena_borodataya.webp',
  },
  {
    id: 'barrakuda-polosataya',
    name: 'Striped Barracuda',
    rarity: 'common',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/barrakuda_polosataya.webp',
  },
  {
    id: 'karanks-polosatiy',
    name: 'Sixband Trevally',
    rarity: 'common',
    meanWeightKg: 0.9,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/karanks_polosatiy.webp',
  },
  {
    id: 'kefal',
    name: 'Flathead Grey Mullet',
    rarity: 'uncommon',
    meanWeightKg: 1,
    weightVarianceKg: 0.5,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/kefal.webp',
  },
  {
    id: 'kambala',
    name: 'Sea Flounder',
    rarity: 'uncommon',
    meanWeightKg: 0.8,
    weightVarianceKg: 0.4,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/kambala.webp',
  },
  {
    id: 'piksha',
    name: 'Haddock',
    rarity: 'uncommon',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/piksha.webp',
  },
  {
    id: 'sayra',
    name: 'Pacific Saury',
    rarity: 'uncommon',
    meanWeightKg: 0.3,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/sayra.webp',
  },
  {
    id: 'letuchaya-ryba',
    name: 'Flying Fish',
    rarity: 'uncommon',
    meanWeightKg: 0.4,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/letuchaya_ryba.webp',
  },
  {
    id: 'tilyapiya-mozambikskaya',
    name: 'Mozambique Tilapia',
    rarity: 'uncommon',
    meanWeightKg: 1,
    weightVarianceKg: 0.5,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/tilyapiya_mozambikskaya.webp',
  },
  {
    id: 'ryba-popugay',
    name: 'Parrotfish',
    rarity: 'uncommon',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/ryba_popugay.webp',
  },
  {
    id: 'babochka-klinopolosaya',
    name: 'Threadfin Butterflyfish',
    rarity: 'uncommon',
    meanWeightKg: 0.2,
    weightVarianceKg: 0.08,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/babochka_klinopolosaya.webp',
  },
  {
    id: 'barabulka-tropicheskaya',
    name: 'Tropical Goatfish',
    rarity: 'uncommon',
    meanWeightKg: 0.5,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/barabulka_tropicheskaya.webp',
  },
  {
    id: 'idol-mavritanskiy',
    name: 'Moorish Idol',
    rarity: 'uncommon',
    meanWeightKg: 0.25,
    weightVarianceKg: 0.1,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/idol_mavritanskiy.webp',
  },
  {
    id: 'ryba-babochka-polosataya',
    name: 'Striped Butterflyfish',
    rarity: 'uncommon',
    meanWeightKg: 0.22,
    weightVarianceKg: 0.09,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/ryba_babochka_polosataya.webp',
  },
  {
    id: 'gobiodon-golubopyatnistiy',
    name: 'Bluespotted Goby',
    rarity: 'uncommon',
    meanWeightKg: 0.03,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/gobiodon_golubopyatnistiy.webp',
  },
  {
    id: 'guban-chistilschik',
    name: 'Cleaner Wrasse',
    rarity: 'uncommon',
    meanWeightKg: 0.03,
    weightVarianceKg: 0.01,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/guban-chistilschik.webp',
  },
  {
    id: 'sergant-major-atlanticheskiy',
    name: 'Atlantic Sergeant Major',
    rarity: 'uncommon',
    meanWeightKg: 0.12,
    weightVarianceKg: 0.05,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/sergant-major_atlanticheskiy.webp',
  },
  {
    id: 'sayda',
    name: 'Pollock',
    rarity: 'uncommon',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/sayda.webp',
  },
  {
    id: 'skumbriya-atlanticheskaya',
    name: 'Atlantic Mackerel',
    rarity: 'uncommon',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.25,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/skumbriya_atlanticheskaya.webp',
  },
  {
    id: 'morskoy-som',
    name: 'Sea Catfish',
    rarity: 'uncommon',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.6,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/morskoy_som.webp',
  },
  {
    id: 'morskoy-sargan',
    name: 'Needlefish',
    rarity: 'uncommon',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/morskoy_sargan.webp',
  },
  {
    id: 'bychok-mangroviy',
    name: 'Bumblebee Goby',
    rarity: 'uncommon',
    meanWeightKg: 0.07,
    weightVarianceKg: 0.03,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/bychok_mangroviy.webp',
  },
  {
    id: 'merlang',
    name: 'Whiting',
    rarity: 'uncommon',
    meanWeightKg: 0.9,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/merlang.webp',
  },
  {
    id: 'grupper-leopardoviy-koralloviy',
    name: 'Leopard Coral Grouper',
    rarity: 'uncommon',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/grupper_leopardoviy_koralloviy.webp',
  },
  {
    id: 'igloryl-aguhon',
    name: 'Agujon Needlefish',
    rarity: 'uncommon',
    meanWeightKg: 0.9,
    weightVarianceKg: 0.4,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/igloryl-aguhon.webp',
  },
  {
    id: 'akula-rifovaya-chernoperaya',
    name: 'Blacktip Reef Shark',
    rarity: 'uncommon',
    meanWeightKg: 15,
    weightVarianceKg: 6,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/akula_rifovaya_chernoperaya.webp',
  },
  {
    id: 'zolotistiy-shiponog',
    name: 'Golden Rabbitfish',
    rarity: 'rare',
    meanWeightKg: 0.5,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/zolotistiy_shiponog.webp',
  },
  {
    id: 'hirurg-goluboy',
    name: 'Blue Tang',
    rarity: 'rare',
    meanWeightKg: 0.4,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/hirurg_goluboy.webp',
  },
  {
    id: 'vyrezub',
    name: 'Black Sea Shemaya',
    rarity: 'rare',
    meanWeightKg: 1.4,
    weightVarianceKg: 0.6,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/vyrezub.webp',
  },
  {
    id: 'sigan-korichnevopyatnistiy',
    name: 'Brown-spotted Rabbitfish',
    rarity: 'rare',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.25,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/sigan_korichnevopyatnistiy.webp',
  },
  {
    id: 'hirurg-polosatiy',
    name: 'Striped Surgeonfish',
    rarity: 'rare',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/hirurg_polosatiy.webp',
  },
  {
    id: 'gramma-korolevskaya',
    name: 'Royal Gramma',
    rarity: 'rare',
    meanWeightKg: 0.02,
    weightVarianceKg: 0.008,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/gramma_korolevskaya.webp',
  },
  {
    id: 'angel-korolevskiy',
    name: 'Queen Angelfish',
    rarity: 'rare',
    meanWeightKg: 0.4,
    weightVarianceKg: 0.15,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/angel_korolevskiy.webp',
  },
  {
    id: 'treska',
    name: 'Cod',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1.5,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/treska.webp',
  },
  {
    id: 'morskaya-forel',
    name: 'Sea Trout',
    rarity: 'rare',
    meanWeightKg: 1.5,
    weightVarianceKg: 0.7,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/morskaya_forel.webp',
  },
  {
    id: 'lavrak',
    name: 'Sea Bass',
    rarity: 'rare',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/lavrak.webp',
  },
  {
    id: 'dorado',
    name: 'Dorado',
    rarity: 'rare',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/dorado.webp',
  },
  {
    id: 'vahu',
    name: 'Wahoo',
    rarity: 'rare',
    meanWeightKg: 10,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/vahu.webp',
  },
  {
    id: 'albakor',
    name: 'Albacore',
    rarity: 'rare',
    meanWeightKg: 18,
    weightVarianceKg: 7,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/albakor.webp',
  },
  {
    id: 'snuk',
    name: 'Snook',
    rarity: 'rare',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/snuk.webp',
  },
  {
    id: 'mangroviy-snapper',
    name: 'Mangrove Snapper',
    rarity: 'rare',
    meanWeightKg: 2,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/mangroviy_snapper.webp',
  },
  {
    id: 'kostlyavaya-ryba',
    name: 'Bonefish',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/kostlyavaya_ryba.webp',
  },
  {
    id: 'ispanskaya-makrel',
    name: 'Spanish Mackerel',
    rarity: 'rare',
    meanWeightKg: 4,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/ispanskaya_makrel.webp',
  },
  {
    id: 'spinorog-titan',
    name: 'Titan Triggerfish',
    rarity: 'rare',
    meanWeightKg: 3,
    weightVarianceKg: 1,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/spinorog_titan.webp',
  },
  {
    id: 'gorbusha',
    name: 'Pink Salmon',
    rarity: 'rare',
    meanWeightKg: 1.8,
    weightVarianceKg: 0.8,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/gorbusha.webp',
  },
  {
    id: 'keta',
    name: 'Chum Salmon',
    rarity: 'rare',
    meanWeightKg: 4.5,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/keta.webp',
  },
  {
    id: 'murena-zvezdchataya',
    name: 'Starry Moray',
    rarity: 'rare',
    meanWeightKg: 1.2,
    weightVarianceKg: 0.5,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/murena_zvezdchataya.webp',
  },
  {
    id: 'krylaka-zebrovaya',
    name: 'Zebra Lionfish',
    rarity: 'rare',
    meanWeightKg: 0.7,
    weightVarianceKg: 0.3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/krylaka_zebrovaya.webp',
  },
  {
    id: 'ryba-fleita',
    name: 'Trumpetfish',
    rarity: 'rare',
    meanWeightKg: 0.6,
    weightVarianceKg: 0.25,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/ryba-fleita.webp',
  },
  {
    id: 'tyurbo',
    name: 'Turbot',
    rarity: 'epic',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/tyurbo.webp',
  },
  {
    id: 'ryba-luna',
    name: 'Ocean Sunfish',
    rarity: 'epic',
    meanWeightKg: 220,
    weightVarianceKg: 90,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/ryba_luna.webp',
  },
  {
    id: 'molochnaya-ryba',
    name: 'Milkfish',
    rarity: 'epic',
    meanWeightKg: 3.5,
    weightVarianceKg: 1.5,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/molochnaya_ryba.webp',
  },
  {
    id: 'angel-imperatorskiy',
    name: 'Emperor Angelfish',
    rarity: 'epic',
    meanWeightKg: 0.5,
    weightVarianceKg: 0.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/angel_imperatorskiy.webp',
  },
  {
    id: 'mandarinivaya-ryba',
    name: 'Mandarin Dragonet',
    rarity: 'epic',
    meanWeightKg: 0.03,
    weightVarianceKg: 0.015,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/mandarinivaya_ryba.webp',
  },
  {
    id: 'losos-atlanticheskiy',
    name: 'Atlantic Salmon',
    rarity: 'epic',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/losos_atlanticheskiy.webp',
  },
  {
    id: 'parusnik',
    name: 'Sailfish',
    rarity: 'epic',
    meanWeightKg: 30,
    weightVarianceKg: 12,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/parusnik.webp',
  },
  {
    id: 'ryba-mech',
    name: 'Swordfish',
    rarity: 'epic',
    meanWeightKg: 55,
    weightVarianceKg: 25,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/ryba_mech.webp',
  },
  {
    id: 'akula-mako',
    name: 'Mako Shark',
    rarity: 'epic',
    meanWeightKg: 70,
    weightVarianceKg: 30,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/akula_mako.webp',
  },
  {
    id: 'barramundi',
    name: 'Barramundi',
    rarity: 'epic',
    meanWeightKg: 10,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/barramundi.webp',
  },
  {
    id: 'goluboy-trevalli',
    name: 'Blue Trevally',
    rarity: 'epic',
    meanWeightKg: 5,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/goluboy_trevalli.webp',
  },
  {
    id: 'barrakuda-bolschaya',
    name: 'Great Barracuda',
    rarity: 'epic',
    meanWeightKg: 12,
    weightVarianceKg: 6,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/barrakuda_bolschaya.webp',
  },
  {
    id: 'permit',
    name: 'Permit',
    rarity: 'epic',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/permit.webp',
  },
  {
    id: 'koralloviy-grupper',
    name: 'Coral Grouper',
    rarity: 'epic',
    meanWeightKg: 5,
    weightVarianceKg: 2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/koralloviy_grupper.webp',
  },
  {
    id: 'katran-simple',
    name: 'Spiny Dogfish',
    rarity: 'epic',
    meanWeightKg: 7,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/katran_simple.webp',
  },
  {
    id: 'murena-european',
    name: 'European Moray',
    rarity: 'epic',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/murena_european.webp',
  },
  {
    id: 'pelengas',
    name: 'Pelingas Mullet',
    rarity: 'mythic',
    meanWeightKg: 3,
    weightVarianceKg: 1.2,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/pelengas.webp',
  },
  {
    id: 'kubera',
    name: 'Cubera Snapper',
    rarity: 'mythic',
    meanWeightKg: 12,
    weightVarianceKg: 5,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/kubera.webp',
  },
  {
    id: 'zubatka-pyatnistaya',
    name: 'Spotted Wolffish',
    rarity: 'mythic',
    meanWeightKg: 8,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/zubatka_pyatnistaya.webp',
  },
  {
    id: 'tunec-zeltoperiy',
    name: 'Yellowfin Tuna',
    rarity: 'mythic',
    meanWeightKg: 50,
    weightVarianceKg: 20,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/tunec_zeltoperiy.webp',
  },
  {
    id: 'chyorniy-snuk',
    name: 'Black Snook',
    rarity: 'mythic',
    meanWeightKg: 8,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/chyorniy_snuk.webp',
  },
  {
    id: 'ryba-napoleon',
    name: 'Napoleon Wrasse',
    rarity: 'mythic',
    meanWeightKg: 35,
    weightVarianceKg: 15,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/ryba_napoleon.webp',
  },
  {
    id: 'konger',
    name: 'Conger Eel',
    rarity: 'mythic',
    meanWeightKg: 6,
    weightVarianceKg: 3,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/konger.webp',
  },
  {
    id: 'murena-gigantskaya',
    name: 'Giant Moray',
    rarity: 'mythic',
    meanWeightKg: 14,
    weightVarianceKg: 6,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/murena_gigantskaya.webp',
  },
  {
    id: 'seldyanoy-korol',
    name: 'Oarfish',
    rarity: 'legendary',
    meanWeightKg: 120,
    weightVarianceKg: 50,
    isPredator: false,
    water: 'salt',
    image: '/riverking/fish/seldyanoy_korol.webp',
  },
  {
    id: 'paltus',
    name: 'Halibut',
    rarity: 'legendary',
    meanWeightKg: 20,
    weightVarianceKg: 10,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/paltus.webp',
  },
  {
    id: 'beluga',
    name: 'Beluga',
    rarity: 'legendary',
    meanWeightKg: 40,
    weightVarianceKg: 20,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/beluga.webp',
  },
  {
    id: 'marlin-siniy',
    name: 'Blue Marlin',
    rarity: 'legendary',
    meanWeightKg: 180,
    weightVarianceKg: 80,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/marlin_siniy.webp',
  },
  {
    id: 'tunets-sineperiy',
    name: 'Bluefin Tuna',
    rarity: 'legendary',
    meanWeightKg: 200,
    weightVarianceKg: 90,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/tunets_sineperiy.webp',
  },
  {
    id: 'tarpon',
    name: 'Tarpon',
    rarity: 'legendary',
    meanWeightKg: 25,
    weightVarianceKg: 12,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/tarpon.webp',
  },
  {
    id: 'gigantskiy-karanks',
    name: 'Giant Trevally',
    rarity: 'legendary',
    meanWeightKg: 25,
    weightVarianceKg: 10,
    isPredator: true,
    water: 'salt',
    image: '/riverking/fish/gigantskiy_karanks.webp',
  },
];

export const locationCatalog: LocationDefinition[] = [
  {
    id: 'pond',
    name: 'Pond',
    description: 'Starter RiverKing location.',
    water: 'fresh',
    unlockWeightKg: 0,
    sizeMultiplier: 1,
    image: '/riverking/backgrounds/pond.webp',
    fishWeights: [
      {
        fishId: 'karas',
        weight: 1.1,
      },
      {
        fishId: 'plotva',
        weight: 1,
      },
      {
        fishId: 'ukleyka',
        weight: 0.7,
      },
      {
        fishId: 'peskar',
        weight: 0.7,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.7,
      },
      {
        fishId: 'yorsh',
        weight: 0.7,
      },
      {
        fishId: 'rotan',
        weight: 0.6,
      },
      {
        fishId: 'gustera',
        weight: 0.5,
      },
      {
        fishId: 'verhoplavka',
        weight: 0.5,
      },
      {
        fishId: 'vyun',
        weight: 0.45,
      },
      {
        fishId: 'okun',
        weight: 0.4,
      },
      {
        fishId: 'lesch',
        weight: 0.4,
      },
      {
        fishId: 'pelyad',
        weight: 0.3,
      },
      {
        fishId: 'yaz',
        weight: 0.25,
      },
      {
        fishId: 'lin',
        weight: 0.2,
      },
      {
        fishId: 'karp',
        weight: 0.15,
      },
      {
        fishId: 'schuka',
        weight: 0.12,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.06,
      },
      {
        fishId: 'som',
        weight: 0.03,
      },
      {
        fishId: 'koi-kohaku',
        weight: 0.01,
      },
      {
        fishId: 'koi-taisho-sanke',
        weight: 0.01,
      },
      {
        fishId: 'koi-showa-sanshoku',
        weight: 0.01,
      },
      {
        fishId: 'koi-utsurimono',
        weight: 0.01,
      },
      {
        fishId: 'koi-bekko',
        weight: 0.01,
      },
      {
        fishId: 'koi-tancho',
        weight: 0.01,
      },
      {
        fishId: 'koi-asagi',
        weight: 0.01,
      },
      {
        fishId: 'koi-shusui',
        weight: 0.01,
      },
      {
        fishId: 'koi-koromo',
        weight: 0.01,
      },
      {
        fishId: 'koi-kinginrin',
        weight: 0.01,
      },
      {
        fishId: 'koi-kawarimono',
        weight: 0.01,
      },
      {
        fishId: 'koi-ogon',
        weight: 0.01,
      },
      {
        fishId: 'koi-hikari-moyomono',
        weight: 0.01,
      },
      {
        fishId: 'koi-goshiki',
        weight: 0.01,
      },
      {
        fishId: 'koi-kumonryu',
        weight: 0.01,
      },
      {
        fishId: 'koi-doitsu',
        weight: 0.01,
      },
    ],
  },
  {
    id: 'swamp',
    name: 'Swamp',
    description:
      'Regular RiverKing location unlocked after 5 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 5,
    sizeMultiplier: 1.15,
    image: '/riverking/backgrounds/swamp.webp',
    fishWeights: [
      {
        fishId: 'rotan',
        weight: 1,
      },
      {
        fishId: 'karas',
        weight: 0.9,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.8,
      },
      {
        fishId: 'gustera',
        weight: 0.7,
      },
      {
        fishId: 'yorsh',
        weight: 0.7,
      },
      {
        fishId: 'vyun',
        weight: 0.6,
      },
      {
        fishId: 'okun',
        weight: 0.6,
      },
      {
        fishId: 'plotva',
        weight: 0.5,
      },
      {
        fishId: 'verhoplavka',
        weight: 0.5,
      },
      {
        fishId: 'peskar',
        weight: 0.4,
      },
      {
        fishId: 'yaz',
        weight: 0.4,
      },
      {
        fishId: 'lin',
        weight: 0.3,
      },
      {
        fishId: 'karp',
        weight: 0.2,
      },
      {
        fishId: 'schuka',
        weight: 0.2,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.1,
      },
      {
        fishId: 'som',
        weight: 0.04,
      },
      {
        fishId: 'zmeegolov-severniy',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'river',
    name: 'River',
    description:
      'Regular RiverKing location unlocked after 20 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 20,
    sizeMultiplier: 1.4,
    image: '/riverking/backgrounds/river.webp',
    fishWeights: [
      {
        fishId: 'plotva',
        weight: 0.9,
      },
      {
        fishId: 'okun',
        weight: 0.9,
      },
      {
        fishId: 'karas',
        weight: 0.8,
      },
      {
        fishId: 'yorsh',
        weight: 0.8,
      },
      {
        fishId: 'bersh',
        weight: 0.75,
      },
      {
        fishId: 'peskar',
        weight: 0.7,
      },
      {
        fishId: 'gustera',
        weight: 0.65,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.6,
      },
      {
        fishId: 'elets',
        weight: 0.6,
      },
      {
        fishId: 'golavl',
        weight: 0.6,
      },
      {
        fishId: 'vyun',
        weight: 0.5,
      },
      {
        fishId: 'vobla',
        weight: 0.5,
      },
      {
        fishId: 'lesch',
        weight: 0.5,
      },
      {
        fishId: 'yaz',
        weight: 0.5,
      },
      {
        fishId: 'sig',
        weight: 0.45,
      },
      {
        fishId: 'chehon',
        weight: 0.4,
      },
      {
        fishId: 'nalim',
        weight: 0.4,
      },
      {
        fishId: 'sudak',
        weight: 0.35,
      },
      {
        fishId: 'karp',
        weight: 0.3,
      },
      {
        fishId: 'zhereh',
        weight: 0.3,
      },
      {
        fishId: 'omul-arcticheskiy',
        weight: 0.25,
      },
      {
        fishId: 'schuka',
        weight: 0.25,
      },
      {
        fishId: 'tolstolobik',
        weight: 0.2,
      },
      {
        fishId: 'muksun',
        weight: 0.2,
      },
      {
        fishId: 'beliy-amur',
        weight: 0.15,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.1,
      },
      {
        fishId: 'som',
        weight: 0.08,
      },
      {
        fishId: 'sterlyad',
        weight: 0.05,
      },
      {
        fishId: 'pelyad',
        weight: 0.04,
      },
      {
        fishId: 'amurskaya-schuka',
        weight: 0.03,
      },
      {
        fishId: 'zmeegolov-severniy',
        weight: 0.02,
      },
      {
        fishId: 'osetr',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'lake',
    name: 'Lake',
    description:
      'Regular RiverKing location unlocked after 80 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 80,
    sizeMultiplier: 1.8,
    image: '/riverking/backgrounds/lake.webp',
    fishWeights: [
      {
        fishId: 'karas',
        weight: 0.9,
      },
      {
        fishId: 'okun',
        weight: 0.9,
      },
      {
        fishId: 'plotva',
        weight: 0.8,
      },
      {
        fishId: 'yorsh',
        weight: 0.8,
      },
      {
        fishId: 'gustera',
        weight: 0.7,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.6,
      },
      {
        fishId: 'bersh',
        weight: 0.6,
      },
      {
        fishId: 'yaz',
        weight: 0.55,
      },
      {
        fishId: 'lesch',
        weight: 0.5,
      },
      {
        fishId: 'golavl',
        weight: 0.5,
      },
      {
        fishId: 'pelyad',
        weight: 0.45,
      },
      {
        fishId: 'sig',
        weight: 0.4,
      },
      {
        fishId: 'nalim',
        weight: 0.4,
      },
      {
        fishId: 'chehon',
        weight: 0.35,
      },
      {
        fishId: 'karp',
        weight: 0.35,
      },
      {
        fishId: 'schuka',
        weight: 0.35,
      },
      {
        fishId: 'peskar',
        weight: 0.3,
      },
      {
        fishId: 'elets',
        weight: 0.3,
      },
      {
        fishId: 'tolstolobik',
        weight: 0.3,
      },
      {
        fishId: 'harius',
        weight: 0.3,
      },
      {
        fishId: 'omul-arcticheskiy',
        weight: 0.25,
      },
      {
        fishId: 'beliy-amur',
        weight: 0.2,
      },
      {
        fishId: 'muksun',
        weight: 0.2,
      },
      {
        fishId: 'som',
        weight: 0.12,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.08,
      },
      {
        fishId: 'sterlyad',
        weight: 0.07,
      },
      {
        fishId: 'lenok',
        weight: 0.06,
      },
      {
        fishId: 'kristivomer',
        weight: 0.05,
      },
      {
        fishId: 'osetr',
        weight: 0.05,
      },
      {
        fishId: 'taymen',
        weight: 0.03,
      },
    ],
  },
  {
    id: 'reservoir',
    name: 'Reservoir',
    description:
      'Regular RiverKing location unlocked after 180 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 180,
    sizeMultiplier: 2.1,
    image: '/riverking/backgrounds/reservoir.webp',
    fishWeights: [
      {
        fishId: 'okun',
        weight: 0.9,
      },
      {
        fishId: 'plotva',
        weight: 0.8,
      },
      {
        fishId: 'karas',
        weight: 0.75,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.75,
      },
      {
        fishId: 'yorsh',
        weight: 0.75,
      },
      {
        fishId: 'ukleyka',
        weight: 0.7,
      },
      {
        fishId: 'bersh',
        weight: 0.65,
      },
      {
        fishId: 'gustera',
        weight: 0.6,
      },
      {
        fishId: 'peskar',
        weight: 0.5,
      },
      {
        fishId: 'yaz',
        weight: 0.5,
      },
      {
        fishId: 'vyun',
        weight: 0.45,
      },
      {
        fishId: 'lesch',
        weight: 0.45,
      },
      {
        fishId: 'nalim',
        weight: 0.45,
      },
      {
        fishId: 'pelyad',
        weight: 0.4,
      },
      {
        fishId: 'schuka',
        weight: 0.3,
      },
      {
        fishId: 'lin',
        weight: 0.25,
      },
      {
        fishId: 'karp',
        weight: 0.25,
      },
      {
        fishId: 'sudak',
        weight: 0.25,
      },
      {
        fishId: 'zhereh',
        weight: 0.25,
      },
      {
        fishId: 'tolstolobik',
        weight: 0.2,
      },
      {
        fishId: 'beliy-amur',
        weight: 0.2,
      },
      {
        fishId: 'muksun',
        weight: 0.15,
      },
      {
        fishId: 'som',
        weight: 0.15,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.1,
      },
      {
        fishId: 'sterlyad',
        weight: 0.05,
      },
      {
        fishId: 'cherniy-amur',
        weight: 0.035,
      },
      {
        fishId: 'osetr',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'mountain-river',
    name: 'Mountain River',
    description:
      'Regular RiverKing location unlocked after 300 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 300,
    sizeMultiplier: 2.3,
    image: '/riverking/backgrounds/mountain_river.webp',
    fishWeights: [
      {
        fishId: 'okun',
        weight: 0.9,
      },
      {
        fishId: 'plotva',
        weight: 0.8,
      },
      {
        fishId: 'ukleyka',
        weight: 0.7,
      },
      {
        fishId: 'golyan',
        weight: 0.65,
      },
      {
        fishId: 'karas',
        weight: 0.6,
      },
      {
        fishId: 'peskar',
        weight: 0.6,
      },
      {
        fishId: 'yorsh',
        weight: 0.6,
      },
      {
        fishId: 'elets',
        weight: 0.5,
      },
      {
        fishId: 'nalim',
        weight: 0.5,
      },
      {
        fishId: 'golavl',
        weight: 0.5,
      },
      {
        fishId: 'yaz',
        weight: 0.45,
      },
      {
        fishId: 'sig',
        weight: 0.4,
      },
      {
        fishId: 'omul-arcticheskiy',
        weight: 0.4,
      },
      {
        fishId: 'forel-ruchevaya',
        weight: 0.4,
      },
      {
        fishId: 'karp',
        weight: 0.35,
      },
      {
        fishId: 'harius',
        weight: 0.3,
      },
      {
        fishId: 'schuka',
        weight: 0.15,
      },
      {
        fishId: 'golets-arkticheskiy',
        weight: 0.1,
      },
      {
        fishId: 'forel-kumzha',
        weight: 0.07,
      },
      {
        fishId: 'lenok',
        weight: 0.06,
      },
      {
        fishId: 'sterlyad',
        weight: 0.05,
      },
      {
        fishId: 'dunaiskiy-losos',
        weight: 0.04,
      },
      {
        fishId: 'taymen',
        weight: 0.03,
      },
      {
        fishId: 'osetr',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'river-delta',
    name: 'River Delta',
    description:
      'Regular RiverKing location unlocked after 450 kg of total catch.',
    water: 'mixed',
    unlockWeightKg: 450,
    sizeMultiplier: 2.5,
    image: '/riverking/backgrounds/river_delta.webp',
    fishWeights: [
      {
        fishId: 'okun',
        weight: 0.9,
      },
      {
        fishId: 'yorsh',
        weight: 0.9,
      },
      {
        fishId: 'seld',
        weight: 0.9,
      },
      {
        fishId: 'bychyok',
        weight: 0.9,
      },
      {
        fishId: 'vobla',
        weight: 0.85,
      },
      {
        fishId: 'koryushka',
        weight: 0.85,
      },
      {
        fishId: 'plotva',
        weight: 0.8,
      },
      {
        fishId: 'kilka',
        weight: 0.8,
      },
      {
        fishId: 'gustera',
        weight: 0.75,
      },
      {
        fishId: 'krasnopyorka',
        weight: 0.75,
      },
      {
        fishId: 'bersh',
        weight: 0.7,
      },
      {
        fishId: 'peskar',
        weight: 0.6,
      },
      {
        fishId: 'mojva',
        weight: 0.6,
      },
      {
        fishId: 'sardina',
        weight: 0.6,
      },
      {
        fishId: 'yaz',
        weight: 0.55,
      },
      {
        fishId: 'anchous',
        weight: 0.55,
      },
      {
        fishId: 'chehon',
        weight: 0.5,
      },
      {
        fishId: 'lesch',
        weight: 0.5,
      },
      {
        fishId: 'nalim',
        weight: 0.5,
      },
      {
        fishId: 'golavl',
        weight: 0.5,
      },
      {
        fishId: 'morskoy-sargan',
        weight: 0.5,
      },
      {
        fishId: 'taran',
        weight: 0.45,
      },
      {
        fishId: 'kefal',
        weight: 0.45,
      },
      {
        fishId: 'kefal-pyatnistaya',
        weight: 0.4,
      },
      {
        fishId: 'sudak',
        weight: 0.35,
      },
      {
        fishId: 'morskoy-som',
        weight: 0.35,
      },
      {
        fishId: 'gorbusha',
        weight: 0.35,
      },
      {
        fishId: 'pelyad',
        weight: 0.3,
      },
      {
        fishId: 'tolstolobik',
        weight: 0.3,
      },
      {
        fishId: 'schuka',
        weight: 0.3,
      },
      {
        fishId: 'keta',
        weight: 0.3,
      },
      {
        fishId: 'beliy-amur',
        weight: 0.25,
      },
      {
        fishId: 'zhereh',
        weight: 0.25,
      },
      {
        fishId: 'morskaya-forel',
        weight: 0.25,
      },
      {
        fishId: 'omul-arcticheskiy',
        weight: 0.2,
      },
      {
        fishId: 'sardina-indiyskaya',
        weight: 0.2,
      },
      {
        fishId: 'kambala',
        weight: 0.2,
      },
      {
        fishId: 'vyrezub',
        weight: 0.2,
      },
      {
        fishId: 'lavrak',
        weight: 0.2,
      },
      {
        fishId: 'som',
        weight: 0.12,
      },
      {
        fishId: 'losos-atlanticheskiy',
        weight: 0.1,
      },
      {
        fishId: 'sterlyad',
        weight: 0.08,
      },
      {
        fishId: 'molochnaya-ryba',
        weight: 0.08,
      },
      {
        fishId: 'ugor-evropeyskiy',
        weight: 0.07,
      },
      {
        fishId: 'cherniy-amur',
        weight: 0.04,
      },
      {
        fishId: 'osetr',
        weight: 0.03,
      },
      {
        fishId: 'pelengas',
        weight: 0.03,
      },
      {
        fishId: 'amurskaya-schuka',
        weight: 0.02,
      },
      {
        fishId: 'beluga',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'sea-coast',
    name: 'Sea Coast',
    description:
      'Regular RiverKing location unlocked after 650 kg of total catch.',
    water: 'salt',
    unlockWeightKg: 650,
    sizeMultiplier: 2.8,
    image: '/riverking/backgrounds/sea_coast.webp',
    fishWeights: [
      {
        fishId: 'seld',
        weight: 0.9,
      },
      {
        fishId: 'koryushka',
        weight: 0.9,
      },
      {
        fishId: 'kilka',
        weight: 0.8,
      },
      {
        fishId: 'sardina',
        weight: 0.8,
      },
      {
        fishId: 'anchous',
        weight: 0.8,
      },
      {
        fishId: 'bychyok',
        weight: 0.8,
      },
      {
        fishId: 'mojva',
        weight: 0.7,
      },
      {
        fishId: 'klyuvach-pacificocean',
        weight: 0.7,
      },
      {
        fishId: 'taran',
        weight: 0.65,
      },
      {
        fishId: 'stavrida',
        weight: 0.6,
      },
      {
        fishId: 'kefal',
        weight: 0.5,
      },
      {
        fishId: 'barabulka-tropicheskaya',
        weight: 0.5,
      },
      {
        fishId: 'skumbriya-atlanticheskaya',
        weight: 0.5,
      },
      {
        fishId: 'morskoy-sargan',
        weight: 0.45,
      },
      {
        fishId: 'merlang',
        weight: 0.4,
      },
      {
        fishId: 'dorado',
        weight: 0.4,
      },
      {
        fishId: 'ispanskaya-makrel',
        weight: 0.4,
      },
      {
        fishId: 'kambala',
        weight: 0.35,
      },
      {
        fishId: 'morskaya-forel',
        weight: 0.35,
      },
      {
        fishId: 'gorbusha',
        weight: 0.35,
      },
      {
        fishId: 'lavrak',
        weight: 0.3,
      },
      {
        fishId: 'vyrezub',
        weight: 0.25,
      },
      {
        fishId: 'keta',
        weight: 0.25,
      },
      {
        fishId: 'murena-zvezdchataya',
        weight: 0.17,
      },
      {
        fishId: 'vahu',
        weight: 0.15,
      },
      {
        fishId: 'losos-atlanticheskiy',
        weight: 0.1,
      },
      {
        fishId: 'tyurbo',
        weight: 0.08,
      },
      {
        fishId: 'katran-simple',
        weight: 0.07,
      },
      {
        fishId: 'murena-european',
        weight: 0.05,
      },
      {
        fishId: 'konger',
        weight: 0.05,
      },
      {
        fishId: 'parusnik',
        weight: 0.04,
      },
      {
        fishId: 'goluboy-trevalli',
        weight: 0.04,
      },
      {
        fishId: 'pelengas',
        weight: 0.04,
      },
      {
        fishId: 'kubera',
        weight: 0.04,
      },
      {
        fishId: 'barrakuda-bolschaya',
        weight: 0.03,
      },
      {
        fishId: 'beluga',
        weight: 0.02,
      },
      {
        fishId: 'tarpon',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'amazon-riverbed',
    name: 'Amazon Riverbed',
    description:
      'Regular RiverKing location unlocked after 900 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 900,
    sizeMultiplier: 3,
    image: '/riverking/backgrounds/amazon_riverbed.webp',
    fishWeights: [
      {
        fishId: 'mecherot-common',
        weight: 0.9,
      },
      {
        fishId: 'tatiya-leopardovaya',
        weight: 0.8,
      },
      {
        fishId: 'tetra-neonovaya',
        weight: 0.75,
      },
      {
        fishId: 'cihlazoma-mezonauta',
        weight: 0.7,
      },
      {
        fishId: 'prohilodus',
        weight: 0.65,
      },
      {
        fishId: 'brahiplatistoma-tigrovaya',
        weight: 0.65,
      },
      {
        fishId: 'otocinklyus',
        weight: 0.6,
      },
      {
        fishId: 'ancistrus',
        weight: 0.6,
      },
      {
        fishId: 'tetra-rodostomus',
        weight: 0.55,
      },
      {
        fishId: 'tetra-black-neon',
        weight: 0.52,
      },
      {
        fishId: 'karnegiella-mramornaya',
        weight: 0.5,
      },
      {
        fishId: 'tetra-chernaya',
        weight: 0.5,
      },
      {
        fishId: 'piranya-krasnopuzaya',
        weight: 0.5,
      },
      {
        fishId: 'tetra-pingvin',
        weight: 0.46,
      },
      {
        fishId: 'gimnotus-ugrevidniy',
        weight: 0.45,
      },
      {
        fishId: 'tetra-ognennaya',
        weight: 0.42,
      },
      {
        fishId: 'tetra-limonnaya',
        weight: 0.4,
      },
      {
        fishId: 'nannostomus-marginatus',
        weight: 0.4,
      },
      {
        fishId: 'paku-cherniy',
        weight: 0.4,
      },
      {
        fishId: 'pimelodus-pyatnistiy',
        weight: 0.4,
      },
      {
        fishId: 'cihlazoma-severum',
        weight: 0.4,
      },
      {
        fishId: 'oskar',
        weight: 0.35,
      },
      {
        fishId: 'payara',
        weight: 0.35,
      },
      {
        fishId: 'leporinus-polosatiy',
        weight: 0.33,
      },
      {
        fishId: 'mecherot-pyatnistiy',
        weight: 0.32,
      },
      {
        fishId: 'koridoras-shterba',
        weight: 0.3,
      },
      {
        fishId: 'bikuda',
        weight: 0.3,
      },
      {
        fishId: 'schuchya-cihlida',
        weight: 0.3,
      },
      {
        fishId: 'torakatum',
        weight: 0.28,
      },
      {
        fishId: 'metinnis-serebristiy',
        weight: 0.25,
      },
      {
        fishId: 'ramirezi',
        weight: 0.25,
      },
      {
        fishId: 'piranya-chernaya',
        weight: 0.25,
      },
      {
        fishId: 'paku-krasnobryuhiy',
        weight: 0.24,
      },
      {
        fishId: 'pterigopliht-parchoviy',
        weight: 0.22,
      },
      {
        fishId: 'tambaki',
        weight: 0.1,
      },
      {
        fishId: 'pavliniy-okun',
        weight: 0.1,
      },
      {
        fishId: 'diskus',
        weight: 0.08,
      },
      {
        fishId: 'ugor-elektricheskiy',
        weight: 0.08,
      },
      {
        fishId: 'ryba-nozh-chernaya',
        weight: 0.07,
      },
      {
        fishId: 'krasnohvostiy-som',
        weight: 0.06,
      },
      {
        fishId: 'aymara',
        weight: 0.05,
      },
      {
        fishId: 'som-veslonosiy',
        weight: 0.05,
      },
      {
        fishId: 'zungaro',
        weight: 0.04,
      },
      {
        fishId: 'skat-motoro',
        weight: 0.04,
      },
      {
        fishId: 'piraiba',
        weight: 0.03,
      },
      {
        fishId: 'arapayma',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'flooded-forest',
    name: 'Igapo Flooded Forest',
    description:
      'Regular RiverKing location unlocked after 1100 kg of total catch.',
    water: 'fresh',
    unlockWeightKg: 1100,
    sizeMultiplier: 3.05,
    image: '/riverking/backgrounds/flooded_forest.webp',
    fishWeights: [
      {
        fishId: 'tetra-black-neon',
        weight: 0.92,
      },
      {
        fishId: 'tetra-rodostomus',
        weight: 0.9,
      },
      {
        fishId: 'tatiya-leopardovaya',
        weight: 0.9,
      },
      {
        fishId: 'karnegiella-mramornaya',
        weight: 0.8,
      },
      {
        fishId: 'tetra-kardinal',
        weight: 0.75,
      },
      {
        fishId: 'nannostomus',
        weight: 0.7,
      },
      {
        fishId: 'tetra-ognennaya',
        weight: 0.7,
      },
      {
        fishId: 'mecherot-common',
        weight: 0.7,
      },
      {
        fishId: 'otocinklyus',
        weight: 0.65,
      },
      {
        fishId: 'nannostomus-marginatus',
        weight: 0.65,
      },
      {
        fishId: 'tetra-pingvin',
        weight: 0.62,
      },
      {
        fishId: 'cihlazoma-mezonauta',
        weight: 0.6,
      },
      {
        fishId: 'tetra-limonnaya',
        weight: 0.55,
      },
      {
        fishId: 'skalyaria-common',
        weight: 0.5,
      },
      {
        fishId: 'koridoras-shterba',
        weight: 0.5,
      },
      {
        fishId: 'piranya-krasnopuzaya',
        weight: 0.5,
      },
      {
        fishId: 'schuchya-cihlida',
        weight: 0.5,
      },
      {
        fishId: 'koridorus-panda',
        weight: 0.45,
      },
      {
        fishId: 'gimnotus-ugrevidniy',
        weight: 0.45,
      },
      {
        fishId: 'pimelodus-pyatnistiy',
        weight: 0.4,
      },
      {
        fishId: 'bikuda',
        weight: 0.4,
      },
      {
        fishId: 'apistogramma-agassiza',
        weight: 0.35,
      },
      {
        fishId: 'cihlazoma-severum',
        weight: 0.35,
      },
      {
        fishId: 'torakatum',
        weight: 0.32,
      },
      {
        fishId: 'paku-cherniy',
        weight: 0.3,
      },
      {
        fishId: 'metinnis-serebristiy',
        weight: 0.25,
      },
      {
        fishId: 'oskar',
        weight: 0.25,
      },
      {
        fishId: 'leporinus-polosatiy',
        weight: 0.22,
      },
      {
        fishId: 'ramirezi',
        weight: 0.2,
      },
      {
        fishId: 'paku-krasnobryuhiy',
        weight: 0.2,
      },
      {
        fishId: 'ryba-list-amazonskaya',
        weight: 0.2,
      },
      {
        fishId: 'pterigopliht-parchoviy',
        weight: 0.18,
      },
      {
        fishId: 'piranya-chernaya',
        weight: 0.18,
      },
      {
        fishId: 'diskus',
        weight: 0.1,
      },
      {
        fishId: 'ugor-elektricheskiy',
        weight: 0.08,
      },
      {
        fishId: 'skalyaria-altum',
        weight: 0.07,
      },
      {
        fishId: 'ryba-nozh-chernaya',
        weight: 0.07,
      },
      {
        fishId: 'tambaki',
        weight: 0.06,
      },
      {
        fishId: 'aymara',
        weight: 0.06,
      },
      {
        fishId: 'pavliniy-okun',
        weight: 0.06,
      },
      {
        fishId: 'krasnohvostiy-som',
        weight: 0.05,
      },
      {
        fishId: 'surubin',
        weight: 0.05,
      },
      {
        fishId: 'som-veslonosiy',
        weight: 0.05,
      },
      {
        fishId: 'skat-motoro',
        weight: 0.04,
      },
      {
        fishId: 'zungaro',
        weight: 0.03,
      },
      {
        fishId: 'payara',
        weight: 0.02,
      },
      {
        fishId: 'aravana-chernaya',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'mangroves',
    name: 'Mangroves',
    description:
      'Regular RiverKing location unlocked after 1500 kg of total catch.',
    water: 'salt',
    unlockWeightKg: 1500,
    sizeMultiplier: 3.1,
    image: '/riverking/backgrounds/mangroves.webp',
    fishWeights: [
      {
        fishId: 'anchous-tropicheskiy',
        weight: 0.9,
      },
      {
        fishId: 'ryba-kloun',
        weight: 0.9,
      },
      {
        fishId: 'lucian-serebristo-pyatnistiy',
        weight: 0.9,
      },
      {
        fishId: 'kefal-pyatnistaya',
        weight: 0.8,
      },
      {
        fishId: 'sardina-indiyskaya',
        weight: 0.8,
      },
      {
        fishId: 'kefal-mangrovaya',
        weight: 0.8,
      },
      {
        fishId: 'hromis-rifoviy',
        weight: 0.7,
      },
      {
        fishId: 'damsel-zheltohvostiy',
        weight: 0.7,
      },
      {
        fishId: 'skorpena-borodataya',
        weight: 0.7,
      },
      {
        fishId: 'morskoy-konek',
        weight: 0.6,
      },
      {
        fishId: 'karanks-polosatiy',
        weight: 0.6,
      },
      {
        fishId: 'tilyapiya-mozambikskaya',
        weight: 0.5,
      },
      {
        fishId: 'bychok-mangroviy',
        weight: 0.5,
      },
      {
        fishId: 'ryba-popugay',
        weight: 0.45,
      },
      {
        fishId: 'sergant-major-atlanticheskiy',
        weight: 0.45,
      },
      {
        fishId: 'grupper-leopardoviy-koralloviy',
        weight: 0.45,
      },
      {
        fishId: 'barabulka-tropicheskaya',
        weight: 0.4,
      },
      {
        fishId: 'guban-chistilschik',
        weight: 0.4,
      },
      {
        fishId: 'morskoy-sargan',
        weight: 0.4,
      },
      {
        fishId: 'igloryl-aguhon',
        weight: 0.4,
      },
      {
        fishId: 'idol-mavritanskiy',
        weight: 0.35,
      },
      {
        fishId: 'ryba-babochka-polosataya',
        weight: 0.35,
      },
      {
        fishId: 'gobiodon-golubopyatnistiy',
        weight: 0.3,
      },
      {
        fishId: 'morskoy-som',
        weight: 0.25,
      },
      {
        fishId: 'krylaka-zebrovaya',
        weight: 0.24,
      },
      {
        fishId: 'sigan-korichnevopyatnistiy',
        weight: 0.22,
      },
      {
        fishId: 'gramma-korolevskaya',
        weight: 0.22,
      },
      {
        fishId: 'ryba-fleita',
        weight: 0.22,
      },
      {
        fishId: 'zolotistiy-shiponog',
        weight: 0.2,
      },
      {
        fishId: 'angel-korolevskiy',
        weight: 0.2,
      },
      {
        fishId: 'snuk',
        weight: 0.2,
      },
      {
        fishId: 'murena-zvezdchataya',
        weight: 0.2,
      },
      {
        fishId: 'akula-rifovaya-chernoperaya',
        weight: 0.18,
      },
      {
        fishId: 'hirurg-polosatiy',
        weight: 0.18,
      },
      {
        fishId: 'mangroviy-snapper',
        weight: 0.15,
      },
      {
        fishId: 'molochnaya-ryba',
        weight: 0.08,
      },
      {
        fishId: 'mandarinivaya-ryba',
        weight: 0.08,
      },
      {
        fishId: 'barramundi',
        weight: 0.08,
      },
      {
        fishId: 'goluboy-trevalli',
        weight: 0.06,
      },
      {
        fishId: 'murena-gigantskaya',
        weight: 0.05,
      },
      {
        fishId: 'chyorniy-snuk',
        weight: 0.045,
      },
      {
        fishId: 'kubera',
        weight: 0.04,
      },
      {
        fishId: 'tarpon',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'coral-flats',
    name: 'Coral Flats',
    description:
      'Regular RiverKing location unlocked after 2000 kg of total catch.',
    water: 'salt',
    unlockWeightKg: 2000,
    sizeMultiplier: 3.2,
    image: '/riverking/backgrounds/coral_flats.webp',
    fishWeights: [
      {
        fishId: 'damsel-siniy',
        weight: 0.9,
      },
      {
        fishId: 'ryba-kloun',
        weight: 0.9,
      },
      {
        fishId: 'fuziler-zheltohvostiy',
        weight: 0.85,
      },
      {
        fishId: 'hromis-rifoviy',
        weight: 0.85,
      },
      {
        fishId: 'damsel-zheltohvostiy',
        weight: 0.8,
      },
      {
        fishId: 'lucian-serebristo-pyatnistiy',
        weight: 0.8,
      },
      {
        fishId: 'skorpena-borodataya',
        weight: 0.75,
      },
      {
        fishId: 'barrakuda-polosataya',
        weight: 0.6,
      },
      {
        fishId: 'morskoy-konek',
        weight: 0.55,
      },
      {
        fishId: 'karanks-polosatiy',
        weight: 0.55,
      },
      {
        fishId: 'sergant-major-atlanticheskiy',
        weight: 0.55,
      },
      {
        fishId: 'grupper-leopardoviy-koralloviy',
        weight: 0.55,
      },
      {
        fishId: 'idol-mavritanskiy',
        weight: 0.53,
      },
      {
        fishId: 'ryba-babochka-polosataya',
        weight: 0.52,
      },
      {
        fishId: 'babochka-klinopolosaya',
        weight: 0.5,
      },
      {
        fishId: 'barabulka-tropicheskaya',
        weight: 0.5,
      },
      {
        fishId: 'gobiodon-golubopyatnistiy',
        weight: 0.5,
      },
      {
        fishId: 'guban-chistilschik',
        weight: 0.5,
      },
      {
        fishId: 'ispanskaya-makrel',
        weight: 0.5,
      },
      {
        fishId: 'ryba-popugay',
        weight: 0.45,
      },
      {
        fishId: 'zolotistiy-shiponog',
        weight: 0.3,
      },
      {
        fishId: 'krylaka-zebrovaya',
        weight: 0.3,
      },
      {
        fishId: 'sigan-korichnevopyatnistiy',
        weight: 0.28,
      },
      {
        fishId: 'gramma-korolevskaya',
        weight: 0.28,
      },
      {
        fishId: 'angel-korolevskiy',
        weight: 0.26,
      },
      {
        fishId: 'hirurg-goluboy',
        weight: 0.25,
      },
      {
        fishId: 'kostlyavaya-ryba',
        weight: 0.25,
      },
      {
        fishId: 'ryba-fleita',
        weight: 0.25,
      },
      {
        fishId: 'hirurg-polosatiy',
        weight: 0.24,
      },
      {
        fishId: 'spinorog-titan',
        weight: 0.22,
      },
      {
        fishId: 'akula-rifovaya-chernoperaya',
        weight: 0.2,
      },
      {
        fishId: 'murena-zvezdchataya',
        weight: 0.2,
      },
      {
        fishId: 'mangroviy-snapper',
        weight: 0.17,
      },
      {
        fishId: 'mandarinivaya-ryba',
        weight: 0.1,
      },
      {
        fishId: 'angel-imperatorskiy',
        weight: 0.08,
      },
      {
        fishId: 'permit',
        weight: 0.08,
      },
      {
        fishId: 'barrakuda-bolschaya',
        weight: 0.06,
      },
      {
        fishId: 'koralloviy-grupper',
        weight: 0.06,
      },
      {
        fishId: 'ryba-napoleon',
        weight: 0.045,
      },
      {
        fishId: 'kubera',
        weight: 0.04,
      },
      {
        fishId: 'murena-gigantskaya',
        weight: 0.03,
      },
      {
        fishId: 'gigantskiy-karanks',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'fjord',
    name: 'Fjord',
    description:
      'Regular RiverKing location unlocked after 2600 kg of total catch.',
    water: 'salt',
    unlockWeightKg: 2600,
    sizeMultiplier: 3.4,
    image: '/riverking/backgrounds/fjord.webp',
    fishWeights: [
      {
        fishId: 'anchous',
        weight: 0.9,
      },
      {
        fishId: 'bychyok',
        weight: 0.9,
      },
      {
        fishId: 'kilka',
        weight: 0.85,
      },
      {
        fishId: 'mojva',
        weight: 0.8,
      },
      {
        fishId: 'seld-tihookeanskaya',
        weight: 0.8,
      },
      {
        fishId: 'koryushka',
        weight: 0.8,
      },
      {
        fishId: 'seld',
        weight: 0.7,
      },
      {
        fishId: 'sardina',
        weight: 0.7,
      },
      {
        fishId: 'klyuvach-pacificocean',
        weight: 0.65,
      },
      {
        fishId: 'taran',
        weight: 0.55,
      },
      {
        fishId: 'sayda',
        weight: 0.55,
      },
      {
        fishId: 'kambala',
        weight: 0.5,
      },
      {
        fishId: 'treska',
        weight: 0.5,
      },
      {
        fishId: 'sayra',
        weight: 0.45,
      },
      {
        fishId: 'merlang',
        weight: 0.4,
      },
      {
        fishId: 'piksha',
        weight: 0.35,
      },
      {
        fishId: 'skumbriya-atlanticheskaya',
        weight: 0.35,
      },
      {
        fishId: 'morskaya-forel',
        weight: 0.35,
      },
      {
        fishId: 'gorbusha',
        weight: 0.35,
      },
      {
        fishId: 'keta',
        weight: 0.3,
      },
      {
        fishId: 'vyrezub',
        weight: 0.25,
      },
      {
        fishId: 'losos-atlanticheskiy',
        weight: 0.1,
      },
      {
        fishId: 'tyurbo',
        weight: 0.08,
      },
      {
        fishId: 'katran-simple',
        weight: 0.07,
      },
      {
        fishId: 'zubatka-pyatnistaya',
        weight: 0.04,
      },
      {
        fishId: 'konger',
        weight: 0.04,
      },
      {
        fishId: 'paltus',
        weight: 0.02,
      },
    ],
  },
  {
    id: 'open-ocean',
    name: 'Open Ocean',
    description:
      'Regular RiverKing location unlocked after 5000 kg of total catch.',
    water: 'salt',
    unlockWeightKg: 5000,
    sizeMultiplier: 4.2,
    image: '/riverking/backgrounds/open_ocean.webp',
    fishWeights: [
      {
        fishId: 'anchous',
        weight: 0.9,
      },
      {
        fishId: 'stavrida',
        weight: 0.85,
      },
      {
        fishId: 'sardina',
        weight: 0.75,
      },
      {
        fishId: 'seld',
        weight: 0.7,
      },
      {
        fishId: 'seld-tihookeanskaya',
        weight: 0.7,
      },
      {
        fishId: 'klyuvach-pacificocean',
        weight: 0.7,
      },
      {
        fishId: 'kilka',
        weight: 0.6,
      },
      {
        fishId: 'mojva',
        weight: 0.6,
      },
      {
        fishId: 'sayda',
        weight: 0.55,
      },
      {
        fishId: 'anchous-tropicheskiy',
        weight: 0.5,
      },
      {
        fishId: 'barrakuda-polosataya',
        weight: 0.5,
      },
      {
        fishId: 'karanks-polosatiy',
        weight: 0.5,
      },
      {
        fishId: 'skumbriya-atlanticheskaya',
        weight: 0.5,
      },
      {
        fishId: 'sardina-indiyskaya',
        weight: 0.45,
      },
      {
        fishId: 'sayra',
        weight: 0.45,
      },
      {
        fishId: 'morskoy-sargan',
        weight: 0.4,
      },
      {
        fishId: 'merlang',
        weight: 0.4,
      },
      {
        fishId: 'dorado',
        weight: 0.4,
      },
      {
        fishId: 'letuchaya-ryba',
        weight: 0.35,
      },
      {
        fishId: 'tunec-zeltoperiy',
        weight: 0.35,
      },
      {
        fishId: 'treska',
        weight: 0.25,
      },
      {
        fishId: 'albakor',
        weight: 0.25,
      },
      {
        fishId: 'vahu',
        weight: 0.2,
      },
      {
        fishId: 'akula-rifovaya-chernoperaya',
        weight: 0.18,
      },
      {
        fishId: 'parusnik',
        weight: 0.1,
      },
      {
        fishId: 'ryba-mech',
        weight: 0.09,
      },
      {
        fishId: 'katran-simple',
        weight: 0.07,
      },
      {
        fishId: 'ryba-luna',
        weight: 0.06,
      },
      {
        fishId: 'akula-mako',
        weight: 0.06,
      },
      {
        fishId: 'zubatka-pyatnistaya',
        weight: 0.04,
      },
      {
        fishId: 'seldyanoy-korol',
        weight: 0.02,
      },
      {
        fishId: 'marlin-siniy',
        weight: 0.02,
      },
      {
        fishId: 'tunets-sineperiy',
        weight: 0.02,
      },
    ],
  },
];
